**1. 다음은 SoftmaxWithLoss 클래스를 수정한 코드이다. 출력될 5개의 값을 순서대로 쓰시오.**

In [2]:
import sys
sys.path.append('C://Users//HAN//Documents//Deep Learning from Scratch') # 각자의 경로로 수정해주세요.
import numpy as np
from common.functions import softmax, cross_entropy_error

In [7]:
x = np.log([[2,3,5],[7,2,1]])
t = np.array([[0,0,1],[1,0,0]])

y = softmax(x)
loss = cross_entropy_error(y, t)

batch_size = t.shape[0]
print(t.size == y.size)
dx = (y - t) / batch_size
print(dx)

t = np.argmax(t, axis=1)
print(t)

print(t.size == y.size)
dx = y.copy()
dx[np.arange(batch_size), t] -= 1
dx = dx / batch_size
print(dx)

True
[[ 0.1   0.15 -0.25]
 [-0.15  0.1   0.05]]
[2 0]
False
[[ 0.1   0.15 -0.25]
 [-0.15  0.1   0.05]]
