**1. 다음은 전처리  코드이다. 출력될 6개를 순서대로  쓰시오.**

앞의 The와 뒤의 the는 동일하게 취급해야 하므로 대문자 T를 소문자 t로 바꿔줍니다.

In [1]:
import numpy as np

text = 'The sky is very blue and the sky is very beautiful today.'
text = text.lower()
print(text)

the sky is very blue and the sky is very beautiful today.


마침표도 하나의 단어로 취급하려고 합니다.  
분리를 위해 마침표 앞에 빈칸을 삽입합니다.

In [2]:
text = text.replace('.', ' .')
print(text)

the sky is very blue and the sky is very beautiful today .


빈칸을 기준으로 분리해서 리스트를 만듭니다.

In [3]:
words = text.split(' ')
print(words)

['the', 'sky', 'is', 'very', 'blue', 'and', 'the', 'sky', 'is', 'very', 'beautiful', 'today', '.']


인공지능이 이해할수 있는 언어는 숫자 뿐입니다.  
등장 순서로 단어에 인덱스를 부여해서 사전을 만듭니다.

In [4]:
word_to_id = {}
id_to_word = {}

for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word

print(word_to_id)
print(id_to_word)

{'the': 0, 'sky': 1, 'is': 2, 'very': 3, 'blue': 4, 'and': 5, 'beautiful': 6, 'today': 7, '.': 8}
{0: 'the', 1: 'sky', 2: 'is', 3: 'very', 4: 'blue', 5: 'and', 6: 'beautiful', 7: 'today', 8: '.'}


위에서 만든 사전을 이용해서 말뭉치를 번역합니다.

In [5]:
corpus = np.array([word_to_id[w] for w in words])
print(corpus)

[0 1 2 3 4 5 0 1 2 3 6 7 8]


**2.(i) 어휘들의 희소 표현(sparse representation)을 통해 말뭉치(corpus)를 행렬로 표현하시오.**

**(ii) 코드를 작성하여 출력하시오.**

In [6]:
sparse = np.zeros((len(corpus),len(word_to_id)))
sparse[np.arange(len(corpus)),corpus] = 1
print(sparse)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**3.(i) 윈도우 크기를 1로 잡았을 때 말뭉치(corpus)의 동시발생 행렬(co-occurrence matrix)을 구하시오.**

**(ii) 윈도우 크기를 2로 잡았을 때 말뭉치(corpus)의 동시발생 행렬(co-occurrence matrix)을 구하시오.**

**(iii) `create_co_matrix` 함수를 이용하여 확인하시오.**

In [7]:
import sys
sys.path.append('C://Users//HAN//Documents//Deep Learning from Scratch 2') # 각자의 경로로 수정해주세요.
from common.util import create_co_matrix

vocab_size = len(word_to_id)
co_matrix_1 = create_co_matrix(corpus, vocab_size)
print(co_matrix_1)
print('='*30)
co_matrix_2 = create_co_matrix(corpus, vocab_size,2)
print(co_matrix_2)

[[0 2 0 0 0 1 0 0 0]
 [2 0 2 0 0 0 0 0 0]
 [0 2 0 2 0 0 0 0 0]
 [0 0 2 0 1 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [1 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 0]]
[[0 2 2 0 1 1 0 0 0]
 [2 0 2 2 0 1 0 0 0]
 [2 2 0 2 1 0 1 0 0]
 [0 2 2 0 1 1 1 1 0]
 [1 0 1 1 0 1 0 0 0]
 [1 1 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 1 1]
 [0 0 0 1 0 0 1 0 1]
 [0 0 0 0 0 0 1 1 0]]


**4.(i) 위 희소표현과 동시발생 행렬 각각에 대해 blue와 beautiful의 코사인 유사도(cosine similarity) 값을 구하시오.**

**(ii) cos_similarity 함수를 이용하여 확인하시오.**

In [8]:
blue_1 = co_matrix_1[word_to_id['blue']]
print(blue_1)

beautiful_1 = co_matrix_1[word_to_id['beautiful']]
print(beautiful_1)

[0 0 0 1 0 1 0 0 0]
[0 0 0 1 0 0 0 1 0]


윈도우 크기가 1일때 blue와 beautiful의 벡터 표현은 각각 $(0,0,0,1,0,1,0,0,0)$, $(0,0,0,1,0,0,0,1,0)$입니다.  
코사인 유사도 값은
$$
{(0,0,0,1,0,1,0,0,0) \circ (0,0,0,1,0,0,0,1,0) \over \|(0,0,0,1,0,1,0,0,0)\| \|(0,0,0,1,0,0,0,1,0)\|} = {1 \over \sqrt{2}\times\sqrt{2}} = {1 \over 2}
$$
입니다.

In [9]:
blue_2 = co_matrix_2[word_to_id['blue']]
print(blue_2)

beautiful_2 = co_matrix_2[word_to_id['beautiful']]
print(beautiful_2)

[1 0 1 1 0 1 0 0 0]
[0 0 1 1 0 0 0 1 1]


윈도우 크기가 2일때 blue와 beautiful의 벡터 표현은 각각 $(1,0,1,1,0,1,0,0,0)$, $(0,0,1,1,0,0,0,1,1)$입니다.  
코사인 유사도 값은
$$
{(1,0,1,1,0,1,0,0,0) \circ (0,0,1,1,0,0,0,1,1) \over \|(1,0,1,1,0,1,0,0,0)\| \|(0,0,1,1,0,0,0,1,1)\|} = {2 \over 2 \times 2} ={1 \over 2}
$$
입니다.

cos_similarity 함수로 검산해보죠.

In [10]:
from common.util import cos_similarity

print(cos_similarity(blue_1, beautiful_1))

print(cos_similarity(blue_2, beautiful_2))

0.49999999292893216
0.49999999500000003
