**1. 다음 말뭉치(corpus)에 대해서  윈도우 크기를 1과 2로 잡았을 때 교재 코드를 사용하여 PPMI행렬을 각각 출력하시오.**

**The sky is very blue and the sky is very beautiful today.**

In [1]:
import sys
sys.path.append('C://Users//HAN//Documents//Deep Learning from Scratch 2') # 각자의 경로로 수정해주세요.
import numpy as np
from common.util import preprocess, create_co_matrix, cos_similarity, ppmi

text = 'The sky is very blue and the sky is very beautiful today.'
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C1 = create_co_matrix(corpus, vocab_size)
W1 = ppmi(C1)
np.set_printoptions(precision=3)
print(W1)

[[0.    2.    0.    0.    0.    2.    0.    0.    0.   ]
 [2.    0.    1.585 0.    0.    0.    0.    0.    0.   ]
 [0.    1.585 0.    1.585 0.    0.    0.    0.    0.   ]
 [0.    0.    1.585 0.    1.585 0.    1.585 0.    0.   ]
 [0.    0.    0.    1.585 0.    2.585 0.    0.    0.   ]
 [2.    0.    0.    0.    2.585 0.    0.    0.    0.   ]
 [0.    0.    0.    1.585 0.    0.    0.    2.585 0.   ]
 [0.    0.    0.    0.    0.    0.    2.585 0.    3.585]
 [0.    0.    0.    0.    0.    0.    0.    3.585 0.   ]]


In [2]:
C2 = create_co_matrix(corpus, vocab_size, 2)
W2 = ppmi(C2)
print(W2)

[[0.    1.131 0.939 0.    0.939 0.939 0.    0.    0.   ]
 [1.131 0.    0.716 0.716 0.    0.716 0.    0.    0.   ]
 [0.939 0.716 0.    0.524 0.524 0.    0.524 0.    0.   ]
 [0.    0.716 0.524 0.    0.524 0.524 0.524 0.939 0.   ]
 [0.939 0.    0.524 0.524 0.    1.524 0.    0.    0.   ]
 [0.939 0.716 0.    0.524 1.524 0.    0.    0.    0.   ]
 [0.    0.    0.524 0.524 0.    0.    0.    1.939 2.524]
 [0.    0.    0.    0.939 0.    0.    1.939 0.    2.939]
 [0.    0.    0.    0.    0.    0.    2.524 2.939 0.   ]]


**2.확률 변수 $X$, $Y$의 확률분포가 다음과 같이 주어져 있다.
$$
\begin{matrix}
Y \backslash X&1&2&3&4 \\\hline
1 &1/8&1/16&1/32&1/32 \\
2 &1/16&1/8&1/32&1/32 \\
3 &1/16&1/16&1/16&1/16 \\
4 &1/4&0&0&0\\\hline
\end{matrix}
$$**

**(i) PMI 테이블과 PPMI 테이블을 구하시오.**

동시발생행렬로부터 PMI 행렬을 만들때는 먼저 전체 합으로 나눠서 확률분포로 변형합니다.  
이 문제는 주어진 테이블이 이미 확률분포이므로 전체 합으로 나눌 필요가 없습니다.  
행과 열을 합해서 marginal distribution을 먼저 구하죠.
$$
\begin{matrix}
&Y&X \\\hline
1 &1/4&1/2 \\
2 &1/4&1/4 \\
3 &1/4&1/8 \\
4 &1/4&1/8 \\\hline
\end{matrix}
$$
pointwise mutual information $\log_2 {p(y,x) \over p(y)p(x)}$를 적용하면
$$
\begin{matrix}
Y \backslash X&1&2&3&4 \\\hline
1 &\log_2 {1/8 \over 1/4 \times 1/2}&\log_2 {1/16 \over 1/4 \times 1/4}&\log_2 {1/32 \over 1/4 \times 1/8}&\log_2 {1/32 \over 1/4 \times 1/8} \\
2 &\log_2 {1/16 \over 1/4 \times 1/2}&\log_2 {1/8 \over 1/4 \times 1/4}&\log_2 {1/32 \over 1/4 \times 1/8}&\log_2 {1/32 \over 1/4 \times 1/8} \\
3 &\log_2 {1/16 \over 1/4 \times 1/2}&\log_2 {1/16 \over 1/4 \times 1/4}&\log_2 {1/16 \over 1/4 \times 1/8}&\log_2 {1/16 \over 1/4 \times 1/8} \\
4 &\log_2 {1/4 \over 1/4 \times 1/2}&\log_2 {0 \over 1/4 \times 1/4}&\log_2 {0 \over 1/4 \times 1/8}&\log_2 {0 \over 1/4 \times 1/8}\\\hline
\end{matrix}
$$
이고 정리하면 다음과 같은 PMI 행렬을 얻습니다.
$$
\begin{matrix}
Y \backslash X&1&2&3&4 \\\hline
1 &0&0&0&0 \\
2 &-1&1&0&0 \\
3 &-1&0&1&1 \\
4 &1&-\infty&-\infty&-\infty\\\hline
\end{matrix}
$$
여기에서 음수를 0으로 모두 바꿔버리면 PPMI 행렬을 쉽게 얻습니다.
$$
\begin{matrix}
Y \backslash X&1&2&3&4 \\\hline
1 &0&0&0&0 \\
2 &0&1&0&0 \\
3 &0&0&1&1 \\
4 &1&0&0&0\\\hline
\end{matrix}
$$

**(ii) 교재의 PPMI 코드는 대칭행렬을 가정하고 작성된 코드이다. 일반적인 행렬에도 적용되도록 코드를 수정한뒤 (i)의 결과를 검산하시오.**

교재의 PPMI 코드를 그대로 적용하면 손으로 계산한 결과와 맞아 떨어지지 않습니다.

In [3]:
table = np.array([[1/8,1/16,1/32,1/32],[1/16,1/8,1/32,1/32],[1/16,1/16,1/16,1/16],[1/4,0,0,0]])
W = ppmi(table)
print(W)

[[0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 1.000e+00 1.443e-08 1.443e-08]
 [1.443e-08 1.000e+00 2.000e+00 2.000e+00]
 [2.000e+00 0.000e+00 0.000e+00 0.000e+00]]


다음은 교재의 PPMI 코드인데 S는 열들의 합이어서 이 문제에서는 $X$의 확률분포가 됩니다.  
동시발생행렬은 항상 대칭행렬이므로 `np.log2(C[i, j] * N / (S[j]*S[i])`는 별 문제없이 작동합니다.  
이 예제는 대칭행렬이 아니므로 그대로 적용하면 안됩니다.

In [4]:
def ppmi(C, verbose=False, eps = 1e-8):    
    M = np.zeros_like(C, dtype=np.float32)
    N = np.sum(C)
    S = np.sum(C, axis=0)
    total = C.shape[0] * C.shape[1]
    cnt = 0

    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            pmi = np.log2(C[i, j] * N / (S[j]*S[i]) + eps)
            M[i, j] = max(0, pmi)

            if verbose:
                cnt += 1
                if cnt % (total//100) == 0:
                    print('%.1f%% 완료' % (100*cnt/total))
    return M

행의 합을 따로 정의하고 pmi 값에 이를 반영하도록 ppmi 코드를 수정합니다.  
그러면 위 손 계산과 일치한 결과가 나옵니다.

In [5]:
def ppmi(C, verbose=False, eps = 1e-8):    
    M = np.zeros_like(C, dtype=np.float32)
    N = np.sum(C)
    S_col = np.sum(C, axis=0)
    S_row = np.sum(C, axis=1)
    total = C.shape[0] * C.shape[1]
    cnt = 0

    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            pmi = np.log2(C[i, j] * N / (S_col[j]*S_row[i]) + eps)
            M[i, j] = max(0, pmi)

            if verbose:
                cnt += 1
                if cnt % (total//100) == 0:
                    print('%.1f%% 완료' % (100*cnt/total))
    return M

W = ppmi(table)
print(W)

[[1.443e-08 1.443e-08 1.443e-08 1.443e-08]
 [0.000e+00 1.000e+00 1.443e-08 1.443e-08]
 [0.000e+00 1.443e-08 1.000e+00 1.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 0.000e+00]]


**3. `count_method_big.py`를 기반으로 다음 코드를 작성하시오.**

**(i) 동시발생행렬과 PPMI행렬 계산결과를 pickle파일에 저장하시오.**

In [6]:
from dataset import ptb
import pickle

window_size = 2

corpus, word_to_id, id_to_word = ptb.load_data('train')
vocab_size = len(word_to_id)
print('동시발생 수 계산 ...')
C = create_co_matrix(corpus, vocab_size, window_size)
print('PPMI 계산 ...')
W = ppmi(C)
data=[C,W]
with open('data.pkl', 'wb') as f:
    pickle.dump(data,f)
print("Saved!")

동시발생 수 계산 ...
PPMI 계산 ...


C:\Users\HAN\anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
C:\Users\HAN\anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in log2
  # This is added back by InteractiveShellApp.init_path()


Saved!


**(ii) (i)의 pickle파일을 불러온 후 PPMI행렬 대신 동시발생행렬에 대하여 SVD를 적용한 후 you, year, car, toyota와 코사인 유사도가 가장 높은 5개의 단어를 출력하시오. 기존 결과와 비교하고 이유를 해석하시오.**

교재에서는 동시발생행렬 → PPMI 행렬 → 차원축소의 과정을 거쳐 벡터표현을 얻었습니다.  
동시발생행렬은 주변 단어의 개수를 세어서 얻어진 단어들의 벡터 표현입니다.  
사람을 알기 위해 그 친구를 보는 셈이지요.  
하지만, a나 the와 같이 너무 자주 등장하는 단어는 등장빈도에 비해 정보를 많이 주지는 않습니다.  
반대로 비사교적인 사람의 친구는 취미라던지 어딘가 통하는 게 있겠지요.  
PPMI는 등장빈도가 적을 수록 더 가중치를 부여합니다.  
이를 통해 단어의 벡터표현이 단어의 의미를 더 많이 담아 내도록 합니다.  
PPMI 행렬이 실제로 이런 역할을 하는지 실험을 해보죠.  
PPMI 행렬을 건너 띄고 얻는 벡터표현들에 대해 코사인 유사도 값이 높은 단어들을 확인해보세요.

In [7]:
from common.util import most_similar

with open('data.pkl', 'rb') as f:
    data=pickle.load(f)
print("Loaded!")
C=data[0]
wordvec_size=100

from sklearn.utils.extmath import randomized_svd
U, S, V = randomized_svd(C, n_components=wordvec_size, n_iter=5,random_state=None)

word_vecs = U[:, :wordvec_size]

querys = ['you', 'year', 'car', 'toyota']
for query in querys:
    most_similar(query, word_to_id, id_to_word, word_vecs, top=5)

Loaded!

[query] you
 we: 0.8493554716566818
 survive: 0.6988542518880129
 wondering: 0.5238895279001866
 texans: 0.519372252599928
 relieve: 0.4955882883808545

[query] year
 month: 0.4056048076441138
 discovision: 0.30618598877951
 celebrity: 0.29021387850472974
 microsoft: 0.28416022569030946
 trinity: 0.2732095314089362

[query] car
 wendy: 0.6341232945621402
 kong: 0.634106902719846
 manufacturing: 0.5985899161026185
 filling: 0.5924201150513638
 near-term: 0.5911872493069659

[query] toyota
 mcdonnell: 0.7872455538682231
 motors: 0.7710814798546892
 digital: 0.756499086341536
 mazda: 0.7545255301568434
 brown-forman: 0.74650081028442


**(iii) (i)의 pickle파일을 불러온 후 벡터표현의 차원을 각각 5, 20, 100으로 잡았을 때 you, year, car, toyota와 코사인 유사도가 가장 높은 5개의 단어를 각각 출력하시오. 기존 결과와 비교하고 이유를 해석하시오.**

PTB 데이터셋에 등장하는 어휘는 10,000개이기 때문에 PPMI 행렬을 통해 얻은 단어의 벡터 표현은 무려 10,000차원입니다.  
신경망의 입력 뉴런의 개수도 10,000개여야 하는데 학습시간도 오래걸리고 과적합에 빠지기도 쉽습니다.  
교재에서는 SVD를 통해 가급적 정보의 손실은 최소화하면서 벡터의 차원을 100으로 줄입니다.  
벡터의 차원을 줄이면 줄일수록 좋을까요?  
벡터의 차원은 정보를 담을 그릇의 크기와 같습니다.  
차원을 너무 줄이면 중요한 정보조차도 담을 수 없습니다.

In [8]:
with open('data.pkl', 'rb') as f:
    data=pickle.load(f)
print("Loaded!")
W=data[1]
wordvec_size=[5,20,100]

from sklearn.utils.extmath import randomized_svd
U, S, V = randomized_svd(W, n_components=100, n_iter=5,random_state=None)

querys = ['you', 'year', 'car', 'toyota']

for i in wordvec_size:
    word_vecs = U[:, :i]
    print('wordvec_size='+str(i))
    for query in querys:
        most_similar(query, word_to_id, id_to_word, word_vecs, top=5)
    print('='*50)

Loaded!
wordvec_size=5

[query] you
 do: 0.9865080118179321
 we: 0.9854855537414551
 'm: 0.9788055419921875
 how: 0.9775410294532776
 're: 0.9767671823501587

[query] year
 last: 0.9893128871917725
 month: 0.98704993724823
 week: 0.9740935564041138
 yesterday: 0.9726187586784363
 since: 0.9693969488143921

[query] car
 financing: 0.9918797016143799
 global: 0.991134762763977
 internal: 0.9902976751327515
 nation: 0.9878718852996826
 product: 0.9848695397377014

[query] toyota
 dutch: 0.9973098039627075
 nabisco: 0.9933227300643921
 publishes: 0.9928234815597534
 england: 0.9923238754272461
 mining: 0.9916982650756836
wordvec_size=20

[query] you
 'll: 0.9102431535720825
 me: 0.9079532027244568
 i: 0.9015957117080688
 we: 0.8940824270248413
 us: 0.8902565240859985

[query] year
 earlier: 0.8362162113189697
 period: 0.8306176066398621
 months: 0.8146306276321411
 month: 0.8118310570716858
 last: 0.7880735397338867

[query] car
 auto: 0.8481684923171997
 luxury: 0.8027188777923584
 machin